version: "3.8"

services:
  # Master Database (Main Database)
  master-postgres:
    image: postgres:latest
    container_name: master-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: master
    ports:
      - "5432:5432"
    volumes:
      - master-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  # Slave Database One (Replica of Master)
  slave-postgres-one:
    image: postgres:latest
    container_name: slave-postgres-one
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slave-one
    ports:
      - "5431:5432"
    volumes:
      - slave-postgres-one:/var/lib/postgresql/data
    depends_on:
      - master-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  # Slave Database Two (Replica of Master)
  slave-postgres-two:
    image: postgres:latest
    container_name: slave-postgres-two
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slave-two
    ports:
      - "5430:5432"
    volumes:
      - slave-postgres-two:/var/lib/postgresql/data
    depends_on:
      - master-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  prisma:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
      - "5051:443"

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6380:6379"
      - "8001:8001"
    volumes:
      - redis-stack:/var/lib/redis-stack
    environment:
      - REDIS_ARGS=--save 900 1
volumes:
  master-postgres:
  slave-postgres-one:
  slave-postgres-two:
  redis-stack:
